/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const myCustomType = t.iface([], {
  "value": "number",
  "ids": t.array("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  myCustomType,
};
export default exportedTypeSuite;
