// Generated by ts-to-zod
import { z } from 'zod';

export const timeWindowSchema = z.object({
  id: z.string(),
  startTime: z.string(),
  endTime: z.string(),
});

export const crewMemberSchema = z.object({
  id: z.string(),
  name: z.string(),
  unitId: z.string(),
});

export const baseEventSchema = z.object({
  id: z.string(),
  timeWindow: timeWindowSchema,
});

export const aerialEventSchema = baseEventSchema.extend({
  color: z.string().optional(),
  crewMembers: z.array(crewMemberSchema),
});

export const groundEventSchema = baseEventSchema.extend({
  color: z.string().optional(),
});
