// Generated by ts-to-zod
import { z } from 'zod';

export const timeWindowSchema = z.object({
  id: z.string(),
  startTime: z.string(),
  endTime: z.string(),
});

export const eventDTOSchema = z.object({
  id: z.string(),
  color: z.string().optional(),
  timeWindow: timeWindowSchema,
});
